### ISSUE TITLE
Eigenmike B-format Conversion Error

### ISSUE THREAD

**Issue by aidanasingh** [micarraylib/micarraylib#2]
# Eigenmike B-format Conversion Error

When using `marco.get_audio_numpy` to retrieve and convert Eigenmike A files to B files from the MARCo dataset, an error was thrown instead of successful conversion.

## Lines that revealed issue (assumes MARCo dataset and micarraylib are installed and up to date)
```
from scipy.io.wavfile import write
from micarraylib import datasets
marco = datasets.marco(download=False,data_home='/Users/aidanajitsingh/datasets/marco')
a = marco.get_audio_numpy('impulse_response+90d','Eigenmike',fmt='B',N=1)
```

## Error Thrown
```
(N+1)^2 should be less than or equal to the number of channels being combined but (N+1)^2 is 4 and len(clip_names) is 1
```

This is an issue because the Eigenmike generates 32 channels of audio, which satisfies the equation in the error. The error also states that it uses `clip_names` to identify how many channels are being converted, which is an issue since the Eigenmike file is a 32-channel wav with one clip name. 

A solution is to check the number of channels after the data is put in `audio_array`, where the `len(audio_array)` will return the number of channels regardless of if the data was originally independent mono files or a singular multi-channel file.

I am using Python 3.9.6 and Big Sur 11.6

**Comment by iranroman** [comment]
Hello @aidanasingh, thanks a lot for noting this and submitting this issue. What you describe as the root cause sounds indeed like what's causing the problem. We will have to address this so that eigenmike files are accessible in both A and B formats in the MARCO dataset. Would you like to draft a solution and open a Pull Request with your code?
