### ISSUE TITLE
Unable to use parameters of soundata.download function 

### ISSUE THREAD

**Issue by sakshamsingh1** [micarraylib/micarraylib#4]
**Description:**
[download] (https://soundata.readthedocs.io/en/latest/source/soundata.html#soundata.datasets.marco.Dataset.download) function of soundata provides arguments like partial_download, force_overwrite, cleanup but we cannot use it from micarraylib because there is no parameter to update it.
<img width="980" alt="Screenshot 2022-01-27 at 12 33 52 PM" src="https://user-images.githubusercontent.com/31805612/151412853-188dae3f-82f9-448b-86ff-87f18eb58f05.png">

**Solution**
We need to pass arguments and use them [here](https://github.com/micarraylib/micarraylib/blob/f0f6324921ee1fc4afe679f816090b8d1cee7f59/micarraylib/core.py#L161).
<img width="606" alt="Screenshot 2022-01-27 at 12 34 12 PM" src="https://user-images.githubusercontent.com/31805612/151412887-6aeaa911-76f5-44b7-a162-9969445a03ce.png">

**Comment by iranroman** [comment]
Hello @sakshamsingh1 !  

You are very right, those parameters could be useful and they can be passed in the call to `dataset.download()`. If you have time, feel free to draft a PR and send it if you want to implement this. It should be pretty easy.

Cheers!

**Comment by sakshamsingh1** [comment]
Yes, I will create a PR.
